[package]
name = "diurne"
version = "0.1.0"
authors = ["Romain Vaillant <rph.vaillant@gmail.com>"]
edition = "2018"

[dependencies]

toml = "0.5"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
rusqlite = "0.24"
